baseURL = "/"
languageCode = "en-us"
title = "Yao Yue"
theme = "nix"


[params]
  Name = "Yao Yue"
  HeaderUsername = "me"
  HeaderHostname = "yaoyue.org"
  About = """
    Yao lives in San Francisco. You can find her biking or walking around the
    city, taking her kids to the playground, or more likely spending time
    thinking about software and systems.
  """
  ProfilePicture = "images/tf.jpeg"

  # Email = "your_email"
  GithubID = "thinkingfish"
  LinkedInID = "yaoyue-thinkingfish"
  MastodonURL = "https://macaw.social/@thinkingfish"
  BlueskyID = "thinkingfish.bsky.social"
