#!/usr/bin/env bash
# Build every Slidev talk in talks-src/<name>/ into public/talks/<name>/, with
# the correct subpath base. Astro then copies public/ -> dist/ verbatim, so the
# decks ship at https://yaoyue.org/talks/<name>/.
#
# Run this before committing whenever a talk's source changes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/talks-src"
OUT="$ROOT/public/talks"
REDIRECTS="$ROOT/public/_redirects"

names=()
for dir in "$SRC"/*/; do
  name="$(basename "$dir")"
  # Skip scaffolding dirs like _template
  case "$name" in _*) continue ;; esac
  echo "==> building talk: $name"
  (
    cd "$dir"
    [ -d node_modules ] || npm install
    rm -rf "$OUT/$name"
    npx slidev build --base "/talks/$name/" --out "$OUT/$name"
  )
  names+=("$name")
done

# SPA fallback for each talk's (history-mode) slide routes. Cloudflare Pages
# reads the root _redirects, serves existing assets first, and falls back to the
# deck's index.html for slide paths like /talks/<name>/3. Regenerated each run.
{
  echo "# Auto-generated by scripts/build-talks.sh — do not edit by hand."
  for n in "${names[@]}"; do
    echo "/talks/$n/* /talks/$n/index.html 200"
  done
} > "$REDIRECTS"

echo "✓ talks built into public/talks/ ; wrote public/_redirects"
